#!/bin/bash

#  Either:
#    ship covid
#    ship devcovid

REMOTE=website@jrootham.ca
BASE=$1
LOCAL=/home/jrootham/dev/civictech/covid-model-code
MODEL=$LOCAL/model
INFECT=$MODEL/infect

./build

rsync -r $INFECT/* $REMOTE:$BASE
