#!/bin/bash

#  Either:
#    ship covid
#    ship devcovid

REMOTE=jrootham@jrootham.ca
BASE=/var/www/vhosts/jrootham.ca/$1.jrootham.ca
LOCAL=/home/jrootham/dev/civictech/covid-model-code
MODEL=$LOCAL/model
INFECT=$MODEL/infect

./build

rsync -r $INFECT/* $REMOTE:$BASE
