#!/bin/bash

REMOTE=jrootham@jrootham.ca
BASE=/var/www/vhosts/jrootham.ca/covid.jrootham.ca
LOCAL=/home/jrootham/dev/civictech/covid-model-code/model
INFECT=$LOCAL/infect

cp $LOCAL/imageSource/*.png $INFECT/images
cp $LOCAL/imageSource/*.svg $INFECT/images

$LOCAL/generate/generate

rsync -r $INFECT/* $REMOTE:$BASE
