const fs = require('fs');

const args = process.argv.slice(2);
const base = args[0];

const C = makeConstants();
const config = makeConfig();

const stream = fs.createWriteStream(base + "css/generated.css");

stream.write("/* DO NOT EDIT THIS FILE*/\n");

stream.write("#slow-speed{background-color: " + config.stepsPerFrame.slow.colour + ";}\n");
stream.write("#medium-speed{background-color: " + config.stepsPerFrame.medium.colour + ";}\n");
stream.write("#fast-speed{background-color: " + config.stepsPerFrame.fast.colour + ";}\n");
stream.write("#fastest-speed{background-color: " + config.stepsPerFrame.fastest.colour + ";}\n");

stream.write("#no-masks{background-color: " + config.masks.specs.none.colour + ";}\n");
stream.write("#encourage-masks{background-color: " + config.masks.specs.encourage.colour + ";}\n");
stream.write("#require-masks{background-color: " + config.masks.specs.require.colour + ";}\n");
stream.write("#enforce-masks{background-color: " + config.masks.specs.enforce.colour + ";}\n");


stream.write("#no-tests{background-color: " + config.tests.none.colour + ";}\n");
stream.write("#light-tests{background-color: " + config.tests.light.colour + ";}\n");
stream.write("#heavy-tests{background-color: " + config.tests.heavy.colour + ";}\n");

stream.write("#no-trace{background-color: " + config.trace.none.colour + ";}\n");
stream.write("#forward-trace{background-color: " + config.trace.forward.colour + ";}\n");
stream.write("#backward-trace{background-color: " + config.trace.backward.colour + ";}\n");

stream.write("#isolate{background-color: " + config.hotColour + ";}\n");

stream.write(".road-colour{background-color: " + config.road.style + ";}\n");

stream.write(".school-colour{background-color: " + config.workStyle[C.WORKTYPE.SCHOOLS] + ";}\n");
stream.write(".office-colour{background-color: " + config.workStyle[C.WORKTYPE.OFFICES] + ";}\n");
stream.write(".meat-colour{background-color: " + config.workStyle[C.WORKTYPE.MEAT] + ";}\n");

stream.write(".bunkhouse-colour{background-color: " + config.bunkHouse.style + ";}\n");
stream.write(".house-colour{background-color: " + config.house.style + ";}\n");
stream.write(".isolation-colour{background-color: " + config.isolation.style + ";}\n");

stream.write(".church-colour{background-color: " + config.church.style + ";}\n");
stream.write(".bar-colour{background-color: " + config.pub.style + ";}\n");
stream.write(".restaurant-colour{background-color: " + config.restaurant.style + ";}\n");
stream.write(".club-colour{background-color: " + config.club.style + ";}\n");

stream.write(".outside-colour{background-color: " + config.outside.style + ";}\n");
stream.write(".cemetary-colour{background-color: " + config.cemetary.style + ";}\n");

stream.write(".icu-colour{background-color: " + config.hospital.style.icu + ";}\n");
stream.write(".ward-colour{background-color: " + config.hospital.style.ward + ";}\n");
stream.write(".hallway-colour{background-color: " + config.hospital.style.hallway + ";}\n");

