const fs = require('fs');

const args = process.argv.slice(2);
const base = args[0];

const C = makeConstants();
const config = makeConfig();

const stream = fs.createWriteStream(base + "css/generated.css");

stream.write("/* DO NOT EDIT THIS FILE*/\n");

stream.write("#no-masks{background-color: " + config.mask.colour.none + ";}\n");
stream.write("#encourage-masks{background-color: " + config.mask.colour.encourage + ";}\n");
stream.write("#require-masks{background-color: " + config.mask.colour.require + ";}\n");
stream.write("#enforce-masks{background-color: " + config.mask.colour.enforce + ";}\n");


stream.write("#no-test{background-color: " + config.test.colour.none + ";}\n");
stream.write("#light-test{background-color: " + config.test.colour.light + ";}\n");
stream.write("#heavy-test{background-color: " + config.test.colour.heavy + ";}\n");

stream.write("#no-trace{background-color: " + config.trace.colour.none + ";}\n");
stream.write("#forward-trace{background-color: " + config.trace.colour.forward + ";}\n");
stream.write("#backward-trace{background-color: " + config.trace.colour.backward + ";}\n");

stream.write("#isolate{background-color: " + config.hotColour + ";}\n");

stream.write(".road-colour{background-color: " + config.road.style + ";}\n");

stream.write(".school-colour{background-color: " + config.workStyle[C.WORKTYPE.SCHOOLS] + ";}\n");
stream.write(".office-colour{background-color: " + config.workStyle[C.WORKTYPE.OFFICES] + ";}\n");
stream.write(".meat-colour{background-color: " + config.workStyle[C.WORKTYPE.MEAT] + ";}\n");

stream.write(".bunkhouse-colour{background-color: " + config.bunkHouse.style + ";}\n");
stream.write(".house-colour{background-color: " + config.house.style + ";}\n");
stream.write(".isolation-colour{background-color: " + config.isolation.style + ";}\n");

stream.write(".church-colour{background-color: " + config.church.style + ";}\n");
stream.write(".bar-colour{background-color: " + config.pub.style + ";}\n");
stream.write(".restaurant-colour{background-color: " + config.restaurant.style + ";}\n");
stream.write(".club-colour{background-color: " + config.club.style + ";}\n");

stream.write(".outside-colour{background-color: " + config.outside.style + ";}\n");
stream.write(".cemetary-colour{background-color: " + config.cemetary.style + ";}\n");

stream.write(".icu-colour{background-color: " + config.hospital.style.icu + ";}\n");
stream.write(".ward-colour{background-color: " + config.hospital.style.ward + ";}\n");
stream.write(".hallway-colour{background-color: " + config.hospital.style.hallway + ";}\n");

