name: test-local

on: 
  workflow_dispatch:

jobs:
  test-local:
    runs-on: ubuntu-latest
    steps:
      - run: |
#        echo ${{ secrets.FAKE_SSH_KEY }} > foo.txt
        echo bar > foo.txt
        cat foo.txt
