name: upload-to-dev
on: 
  push:
    branches:
      'main'

jobs:
  upload-to-dev:
    environment: basic
    
    uses: ./.github/workflows/upload.yaml
    with:
      target: devcovid
    secrets:
      envKEY: ${{ secrets.PRIVATE_SSH_KEY }}
