name: upload

env:
  TARGET: ${{ inputs.target }}

on: 
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      envKEY:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - uses: actions/checkout@v2

      - run: |
          mkdir -p ~/.ssh/
          echo "$COVID_KEY" > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
        env:
            COVID_KEY: ${{ secrets.PRIVATE_SSH_KEY }}


      - run: |
        cd $GITHUB_WORKSPACE/model
        ./ship $TARGET
        