name: upload

env:
  REMOTE: jrootham@jrootham.ca
  BASE: /var/www/vhosts/jrootham.ca/${{ inputs.target }}.jrootham.ca

on: 
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      envKEY:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - uses: actions/checkout@v2

      - run: |
          mkdir -p ~/.ssh/
          echo echo the string "$COVID_KEY"
          echo padding "$COVID_KEY" > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          ls -l ~/.ssh
          cat ~/.ssh/id_ecdsa
        env:
            COVID_KEY: ${{ secrets.envKEY }}


      - run: $GITHUB_WORKSPACE/model/generate/generate $GITHUB_WORKSPACE

      - run: cp $GITHUB_WORKSPACE/model/imageSource/*.png $GITHUB_WORKSPACE/model/infect/images
      
      - run: echo -rv $GITHUB_WORKSPACE/infect $REMOTE:$BASE

      - run: |
        wc ~/.ssh/id_ecdsa
        scp -rv $GITHUB_WORKSPACE/infect $REMOTE:$BASE



      
