name: upload

env:
  REMOTE: jrootham@jrootham.ca
  BASE: /var/www/vhosts/jrootham.ca/${{ inputs.target }}.jrootham.ca

on: 
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - uses: actions/checkout@v2

      - run: |
          echo $HOME/model/infect $REMOTE:$BASE
          echo ls
          ls
          echo ls $HOME
          ls $HOME
          echo ls $HOME/model
          ls $HOME/model
          echo ls $HOME/model/generate
          ls $HOME/model/generate

      - run: |
          mkdir -p ~/.ssh/
          echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_ecdsa.key
          chmod 600 ~/.ssh/id_ecdsa.key

      - run: $HOME/model/generate/generate $HOME

      - run: cp $HOME/model/imageSource/*.png $HOME/model/infect/images

#      - run: rsync -r $INFECT $REMOTE:$BASE


      
