name: upload

env:
  REMOTE: jrootham@jrootham.ca
  BASE: /var/www/vhosts/jrootham.ca/${{ inputs.target }}.jrootham.ca

on: 
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - uses: actions/checkout@v2

      - run: |
          mkdir -p ~/.ssh/
          echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_ecdsa.key
          chmod 600 ~/.ssh/id_ecdsa.key

      - run: echo $GITHUB_WORKSPACE

      - run: $GITHUB_WORKSPACE/model/generate/generate $GITHUB_WORKSPACE

      - run: cp $GITHUB_WORKSPACE/model/imageSource/*.png $GITHUB_WORKSPACE/model/infect/images

      - run: cat $GITHUB_WORKSPACE/model/infect/css/generated.css
      
#      - run: rsync -r $GITHUB_WORKSPACE/infect $REMOTE:$BASE


      
